name: Build and Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:

    - name: AWS Deploy Action
      run: |
           echo "${{secrets.KEY_EC2_E}}"
           echo "${{secrets.KEY_EC2_E}}" > private_key && chmod 400 private_key
           ssh -o StrictHostKeyChecking=no -i "private_key" ubuntu@ec2-107-20-132-70.compute-1.amazonaws.com "
                     cd /home/ubuntu/eden-api &&
                     git pull &&
                     mvn clean package -DskipTests &&
                     ./executar.sh "

    - name: Render Deploy Action
      uses: johnbeynon/render-deploy-action@747373cdb7b9b3f561438e063ee0815b71584f1b
      with:
        # ID of the service to deploy
        service-id: ${{secrets.SERVICE_ID}}
        # A Render API key
        api-key: ${{secrets.API_KEY}}
        wait-for-success: true
